- name: Copy the azure CLI repo files
  template:
    src: az.repo
    dest: /etc/yum.repos.d/azure-cli.repo

- name: Install Azure CLI
  yum:
    name: azure-cli
    state: present

#INSTALL libicu package install
- name: Install libicu
  yum:
    name: libicu
    state: present

- name: Install the Azure DevOps extension for the Azure CLI
  shell: az extension add --name azure-devops
  become_user: roboshop

- name: Setup PAT for AZ CLI
  shell: echo {{PAT}} |az devops login
  become_user: roboshop

- name: Delete {{COMPONENT}} directory if it exist
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Cretae {{COMPONENT}} directory
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory
  become_user: roboshop

- name: Download the rs{{COMPONENT}} artifacts
  shell: az artifacts universal download --organization "https://dev.azure.com/srimaanaws2021/" --feed "srimaanaws2021" --name "rs{{COMPONENT}}" --version "{{APP_ARTIFACT_VERSION}}" --path "/home/roboshop/{{COMPONENT}}"
#  shell: az artifacts universal download --organization "https://dev.azure.com/srimaanaws2021/" --project "SRI_DEVOPS" --scope project   --feed "srimaanaws2021"   --name "rs{{component}}"   --version "{{APP_ARTIFACT_VERSION}}" --path .
  become_user: roboshop