- name: Setup OS-prerequisites
  include_tasks: os.yml

- name: Install Python Packages
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: Create Application User
  user:
    name: roboshop # no need to check user exits or not..Ansible just take it as command declarative and do

- name: Download the artifacts
  include_tasks: download-az-artifacts.yml # this include other task in common role

- name: Install Python Packages
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip-3
  become_user: roboshop

- name: Update Systemd.service file
  include_tasks: systemd-setup.yml