- name: Copy and Setup Rsyslog
  copy:
    src: roboshop.conf
    dest: /etc/rsyslog.d/roboshop.conf

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: Copy the systemd service file
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} the Service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "{{COMPONENT}}"