- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Delete old content
  ansible.builtin.file:
    path: /usr/share/nginx
    state: absent

- name: Cretae content directory
  ansible.builtin.file:
    path: /usr/share/nginx
    state: directory

- name: Download and Unarchive {{COMPONENT}} zip file
  ansible.builtin.unarchive:
    src: "{{ARTIFACT_ZIP_URL}}"
    dest: /usr/share/nginx
    remote_src: yes

- name: Rename Content Directory
  shell: mv /usr/share/nginx/static /usr/share/nginx/html

- name: Start Nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes