- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Delete old content
  ansible.builtin.file:
    path: /usr/share/nginx
    state: absent

- name: Create content directory
  ansible.builtin.file:
    path: /usr/share/nginx
    state: directory

- name: Download and Unarchive {{COMPONENT}} zip file
  ansible.builtin.git:
    src: "{{ARTIFACT_ZIP_URL}}"
    dest: /usr/share/nginx
#    remote_src: yes

- name: Rename Content Directory
  shell: mv /usr/share/nginx/static /usr/share/nginx/html

- name: Copy the roboshop.conf file and update nginx configuration
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx

- name: Copy the nginx.conf file to update log format
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Start Nginx
  systemd:
    name: nginx
    daemon_reload: yes
    state: started
    enabled: yes

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include filebeat Role
  include_role:
    name: filebeat