- name: Setup Roboshop Project
  hosts: all
  vars:
    domain: devopssri.ml
  become: yes  #acts as sudo user ,it can be mention at task level also
  tasks:
    - name: Load Frontend Role
      import_role:
        name: frontend
      when: component == "frontend"
      tags:
        - frontend

    - name: Load Cart Role
      import_role: # this is playbook so to import role use import_role
        name: cart
      when: component == "cart"
      tags:
        - cart

    - name: Load Catalogue Role
      import_role:
        name: catalogue
      when: component == "catalogue"  #variables in inventory file
      tags:
        - catalogue
#
    - name: Load User Role
      import_role:
        name: user
      when: component == "user"
      tags:
        - user
#
    - name: Load shipping Role
      import_role:
        name: shipping
      when: component == "shipping"
      tags:
        - shipping
#
    - name: Load Payment Role
      import_role:
        name: payment
      when: component == "payment"
      tags:
        - payment

    - name: Load Mongo Role
      import_role:
        name: mongo
      when: component == "mongo"
      tags:
        - mongo

    - name: Load redis Role
      import_role:
        name: redis
      when: component == "redis"
      tags:
        - redis

    - name: Load mysql Role
      import_role:
        name: mysql
      when: component == "mysql"
      tags:
        - mysql

    - name: Load rabbitmq Role
      import_role:
        name: rabbitmq
      when: component == "rabbitmq"
      tags:
        - rabbitmq