- name: Setup Roboshop Project
  hosts: all
  vars:
    domain: devopssri.ml
  become: yes  #acts as sudo user ,it can be mention at task level also
  tasks:
    - name: Load Frontend Role
        name: frontend
        import_role:
        when: component == "frontend"
        tags:
          - frontend

    - name: Load Cart Role
      import_role: # this is playbook so to import role use import_role
        name: cart
      when: component == "cart"
      tags:
        - cart

    - name: Load Catalogue Role
      import_role:
        name: catalogue
      when: component == "catalogue"  #variables in inventory file
      tags:
        - catalogue
#
    - name: Load User Role
      import_role:
        name: user
      when: component == "user"
      tags:
        - user
#
    - name: Load shipping Role
      import_role:
        name: shipping
      when: component == "shipping"
      tags:
        - shipping
#
    - name: Load Payment Role
      import_role:
        name: payment
      when: component == "payment"
      tags:
        - payment