#S34:
- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

#install Erlang
- name: Install the repo file of erlang
  yum:
    name: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_22.2.1-1~centos~7_amd64.rpm
    state: present

#Setup rabbitmq repo
- name: Setup Rabbitmq Repo
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install Rabbitmq
  yum:
    name: rabbitmq-server
    state: present
#
#restart the rabbitmq service by using systemd
- name: Start the rabbitmq-server Service
  systemd:
    state: restarted
    enabled: yes
    name: rabbitmq-server

#Create RoboShop App User in RabbitMQ
- name: Create App user
  shell: rabbitmqctl add_user roboshop roboshop123;rabbitmqctl set_user_tags roboshop administrator;rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"



