#S33:
- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os
#copy mongo repo file using template
- name: Copy the mongo repo file
  template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo
#
#install mongodb
- name: Install Mongodb
  yum:
    name: mongodb-org
    state: present
#
#replace 127.0.0 in mongod.conf unsing replace module
- name: update mongo.conf file
  replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

#restart the mangod service by systemd
- name: Start the Mongod Service
  systemd:
    state: restarted
    enabled: yes
    name: mongod

#downlad the artifacts
- name: Download and Unarchive {{COMPONENT}} zip file
  ansible.builtin.unarchive:
    src: "{{ARTIFACT_ZIP_URL}}"
    dest: /tmp
    remote_src: yes

#load the schema now using shell using loop
- name: Load the schema
  shell: mongo < /tmp/{{item}}.js
  loop:
    - catalogue
    - users
#launch catalogue service now as mongodb is ready
#nslookup dns record name


