- name: Include Common role for JAVA
  include_role:  #this is role to include role ina= a role include_role
    name: common
    tasks_from: java

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include filebeat Role
  include_role:
    name: filebeat