- name: Include Common role
  include_role:  #this is command to include role in a role
    name: common
    tasks_from: nodejs

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include filebeat Role
  include_role:
    name: filebeat